In [117]:
import torch
import torch.nn as nn

# Without sequential module

## Single layer Nueral Network

In [118]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    return self.sigmoid(self.linear(features))

In [119]:
features = torch.rand(20, 10)
features

tensor([[0.4210, 0.0147, 0.8474, 0.1742, 0.1767, 0.6724, 0.6841, 0.6307, 0.1744,
         0.0201],
        [0.6339, 0.4664, 0.2795, 0.3264, 0.3654, 0.3166, 0.7153, 0.4083, 0.0503,
         0.3920],
        [0.6809, 0.4360, 0.0647, 0.9623, 0.3315, 0.0378, 0.7433, 0.7856, 0.9464,
         0.3949],
        [0.4399, 0.0043, 0.7951, 0.2132, 0.3198, 0.1121, 0.5237, 0.9257, 0.1995,
         0.5657],
        [0.3728, 0.9940, 0.4234, 0.9772, 0.0597, 0.4236, 0.8872, 0.7262, 0.5108,
         0.2233],
        [0.0582, 0.0746, 0.8647, 0.0745, 0.3108, 0.6061, 0.7732, 0.1740, 0.8221,
         0.5566],
        [0.8124, 0.8189, 0.6180, 0.0665, 0.6694, 0.4809, 0.7584, 0.2446, 0.6654,
         0.9970],
        [0.6316, 0.5693, 0.0581, 0.4440, 0.4099, 0.4750, 0.6979, 0.3531, 0.6118,
         0.0545],
        [0.5860, 0.9672, 0.4205, 0.5108, 0.4523, 0.5616, 0.8301, 0.0750, 0.0330,
         0.0196],
        [0.4126, 0.7248, 0.5891, 0.4750, 0.7756, 0.0019, 0.3242, 0.0282, 0.9609,
         0.4305],
        [0

In [120]:
model = Model(10)
# model.forward(features) #This also works
model(features) # But this is the standard way of using

tensor([[0.4943],
        [0.5041],
        [0.5248],
        [0.4924],
        [0.5349],
        [0.5257],
        [0.6000],
        [0.5368],
        [0.5368],
        [0.5849],
        [0.5789],
        [0.5305],
        [0.5447],
        [0.5165],
        [0.5385],
        [0.5245],
        [0.5179],
        [0.4885],
        [0.5453],
        [0.5283]], grad_fn=<SigmoidBackward0>)

In [121]:
model.linear.weight

Parameter containing:
tensor([[ 0.1831,  0.2972,  0.1303, -0.1322,  0.0367,  0.0544, -0.1183, -0.0084,
          0.2432,  0.0119]], requires_grad=True)

In [122]:
model.linear.bias

Parameter containing:
tensor([-0.1909], requires_grad=True)

In [123]:
!pip install torchinfo

In [124]:
from torchinfo import summary
summary(model, input_size=(20, 10))
# 11 parameters = 10 weights + 1 bias

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [20, 1]                   --
├─Linear: 1-1                            [20, 1]                   11
├─Sigmoid: 1-2                           [20, 1]                   --
Total params: 11
Trainable params: 11
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## NN with hidden layers

In [125]:
class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 5)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(5, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    return self.sigmoid(self.linear2(self.relu(self.linear1(features))))

In [126]:
model2 = Model2(10)
model2(features)

tensor([[0.5534],
        [0.5378],
        [0.5378],
        [0.5485],
        [0.5586],
        [0.5237],
        [0.5378],
        [0.5403],
        [0.5438],
        [0.5378],
        [0.5577],
        [0.5180],
        [0.5352],
        [0.5427],
        [0.5203],
        [0.5253],
        [0.5157],
        [0.5298],
        [0.5323],
        [0.5238]], grad_fn=<SigmoidBackward0>)

In [127]:
model2.linear1.weight

Parameter containing:
tensor([[-0.3161, -0.0664,  0.0643,  0.2483, -0.3105,  0.1889, -0.1558, -0.2252,
          0.1275, -0.2210],
        [-0.1995,  0.2257,  0.2428, -0.1576, -0.2310, -0.3146, -0.0750,  0.2958,
         -0.1938, -0.1513],
        [-0.2793, -0.3147, -0.0594,  0.0260,  0.1281,  0.1943, -0.1250,  0.1265,
         -0.0235,  0.3063],
        [-0.0527,  0.1889, -0.0633, -0.2247, -0.2140, -0.2158, -0.1865,  0.1544,
         -0.2745, -0.0449],
        [-0.2505, -0.0366, -0.0111,  0.0900, -0.0805,  0.1465,  0.2126, -0.0513,
         -0.0667, -0.2740]], requires_grad=True)

In [128]:
model2.linear2.weight

Parameter containing:
tensor([[-0.3604,  0.4023, -0.3443, -0.0338,  0.1396]], requires_grad=True)

In [129]:
summary(model2, input_size=(20, 10))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [20, 1]                   --
├─Linear: 1-1                            [20, 5]                   55
├─ReLU: 1-2                              [20, 5]                   --
├─Linear: 1-3                            [20, 1]                   6
├─Sigmoid: 1-4                           [20, 1]                   --
Total params: 61
Trainable params: 61
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential Container

In [130]:
class SeqModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 5),
        nn.ReLU(),
        nn.Linear(5, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    return self.network(features)

In [131]:
Seqmodel = SeqModel(10)
Seqmodel(features)

tensor([[0.4232],
        [0.4185],
        [0.4190],
        [0.4230],
        [0.4183],
        [0.4239],
        [0.4185],
        [0.4197],
        [0.4184],
        [0.4199],
        [0.4185],
        [0.4185],
        [0.4184],
        [0.4202],
        [0.4184],
        [0.4195],
        [0.4184],
        [0.4184],
        [0.4183],
        [0.4185]], grad_fn=<SigmoidBackward0>)

#Full Training Pipeline using built in functions

In [132]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [133]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [134]:
df.shape

(569, 33)

In [135]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [136]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [137]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [138]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [139]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [140]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [141]:
print(X_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([455, 30])
torch.Size([455])


## Model

In [142]:
import torch.nn as nn

class Nueralnetwork(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    return self.sigmoid(self.linear(features))

Parameters

In [143]:
learning_rate = 10
epochs = 100

Loss Function

In [144]:
loss_function = nn.BCELoss()

## Training Pipeline

In [145]:
model = Nueralnetwork(X_train_tensor.shape[1])

In [146]:
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [147]:
model.parameters()

<generator object Module.parameters at 0x7d5c877eb920>

In [148]:
for epoch in range(epochs):
  y_pred = model(X_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))  #reshaping y_train for (455) to (455, 1)

  loss.backward()

  optimizer.step()

  optimizer.zero_grad()

  if (epoch+1) % 5 == 0:
    print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')


Epoch: 5, Loss: 0.5720
Epoch: 10, Loss: 0.1598
Epoch: 15, Loss: 0.1280
Epoch: 20, Loss: 0.1110
Epoch: 25, Loss: 0.0999
Epoch: 30, Loss: 0.0919
Epoch: 35, Loss: 0.0854
Epoch: 40, Loss: 0.0799
Epoch: 45, Loss: 0.0752
Epoch: 50, Loss: 0.0709
Epoch: 55, Loss: 0.0671
Epoch: 60, Loss: 0.0635
Epoch: 65, Loss: 0.0603
Epoch: 70, Loss: 0.0574
Epoch: 75, Loss: 0.0547
Epoch: 80, Loss: 0.0522
Epoch: 85, Loss: 0.0500
Epoch: 90, Loss: 0.0480
Epoch: 95, Loss: 0.0462
Epoch: 100, Loss: 0.0446


In [149]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
y_pred = (y_pred > 0.8).float()

In [150]:
accuracy = (y_pred == y_test_tensor).float().mean()
print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5236995816230774
