In [ ]:
import torch

In [ ]:
if torch.cuda.is_available():
  print("cuda is available")
else:
  print("cuda is not available")

cuda is not available


In [ ]:
torch.cuda.is_available()

False

#Ways To create Tensors

In [ ]:
a = torch.empty(2, 3)
print(a)
print(type(a))

tensor([[4.3626e+36, 4.4949e-41, 4.3626e+36],
        [4.4949e-41, 0.0000e+00, 0.0000e+00]])
<class 'torch.Tensor'>


In [ ]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.rand(2, 3)

tensor([[0.9905, 0.6668, 0.9797],
        [0.9762, 0.9335, 0.9267]])

In [ ]:
torch.manual_seed(1)
torch.rand(5,5)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635],
        [0.4550, 0.5725, 0.4980, 0.9371, 0.6556],
        [0.3138, 0.1980, 0.4162, 0.2843, 0.3398]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0, 10, 100)

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

In [ ]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
torch.full((3,3,3), 3)

tensor([[[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]])

# Tensor Shapes

In [ ]:
x = torch.full((4,2,4,2), 1)

In [ ]:
x.shape

torch.Size([4, 2, 4, 2])

In [ ]:
torch.empty_like(x)
torch.ones_like(x)
torch.zeros_like(x)

tensor([[[[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]],


        [[[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]],


        [[[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]],


        [[[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]],

         [[0, 0],
          [0, 0],
          [0, 0],
          [0, 0]]]])

In [ ]:
x.dtype

torch.int64

In [ ]:
y = torch.rand_like(x, dtype = torch.float64)
y

tensor([[[[1.9153e-01, 1.7415e-01],
          [4.7968e-01, 7.9422e-01],
          [3.5545e-01, 7.0672e-02],
          [3.3372e-01, 1.4115e-01]],

         [[3.0761e-01, 4.7367e-02],
          [5.6060e-02, 1.7642e-01],
          [5.6146e-01, 9.2873e-02],
          [2.7691e-02, 2.0635e-01]]],


        [[[3.3007e-01, 2.4143e-01],
          [5.9818e-01, 5.4758e-01],
          [3.4158e-01, 5.8423e-01],
          [1.6151e-01, 6.2033e-02]],

         [[2.2804e-01, 8.7955e-01],
          [9.8284e-01, 1.3406e-02],
          [9.8196e-01, 3.1837e-01],
          [6.8346e-01, 9.1108e-01]]],


        [[[2.4983e-01, 4.9920e-04],
          [9.6079e-01, 1.0211e-01],
          [7.1649e-01, 7.8914e-01],
          [2.5992e-01, 7.3201e-01]],

         [[5.9828e-01, 2.0887e-01],
          [8.2893e-01, 9.8783e-01],
          [3.4568e-01, 9.8503e-01],
          [4.8495e-01, 1.1958e-01]]],


        [[[5.0251e-01, 4.7330e-01],
          [7.8605e-01, 1.4984e-01],
          [7.1350e-01, 8.6805e-01],
          

In [ ]:
y.dtype

torch.float64

#Tensor Data types

In [ ]:
x.dtype

torch.int64

To specify data type while initializing

In [ ]:
x = torch.tensor([1.0, 0.0, 3.0, 4.9], dtype=torch.int64)

In [ ]:
print(x.dtype)

torch.int64


In [ ]:
torch.rand(3,3, dtype = torch.float64)

tensor([[0.8626, 0.4255, 0.2891],
        [0.6929, 0.5390, 0.5908],
        [0.8673, 0.1013, 0.1770]], dtype=torch.float64)

# Math operations


### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7138, 0.5913],
        [0.6235, 0.9991]])

In [ ]:
x + 2
x - 2
x * 3
x / 3
x**2

tensor([[0.5095, 0.3497],
        [0.3888, 0.9981]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [ ]:
a + b
a * b
a / b
a ** b
a % b

tensor([[0.0682, 0.0100, 0.1147],
        [0.1541, 0.8908, 0.0363]])

In [ ]:
x = torch.tensor([1, -2, 3, -4])

In [ ]:
x = torch.neg(x)
x

tensor([-1,  2, -3,  4])

In [ ]:
x = torch.abs(x)
x

tensor([1, 2, 3, 4])

In [ ]:
t = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
torch.round(t)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(t)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(t)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(t, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
t = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
t

tensor([[9., 6., 0.],
        [0., 8., 9.]])

In [ ]:
torch.sum(t)
torch.sum(t, dim=0)
torch.sum(t, dim=1)

tensor([15., 17.])

In [ ]:
torch.mean(t)
torch.mean(t, dim=0)

tensor([4.5000, 7.0000, 4.5000])

In [ ]:
torch.median(t)

tensor(6.)

In [ ]:
torch.max(t)
torch.min(t)

tensor(0.)

In [ ]:
torch.prod(t)

tensor(0.)

In [ ]:
torch.std(t)

tensor(4.2740)

In [ ]:
torch.var(t)

tensor(18.2667)

In [ ]:
torch.argmax(t)

tensor(0)

In [ ]:
torch.argmin(t)

tensor(2)

### 4. Matrix operations

In [ ]:
t1 = torch.randint(size=(2,3), low=0, high=15)
t2 = torch.randint(size=(3,2), low=0, high=15)
print(t1)
print(t2)

tensor([[11,  5,  9],
        [ 6, 14,  8]])
tensor([[ 6,  7],
        [14,  3],
        [11, 10]])


In [ ]:
torch.matmul(t1, t2)

tensor([[235, 182],
        [320, 164]])

In [ ]:
v1 = torch.tensor([1, 1])
v2 = torch.tensor([4, 5])

torch.dot(v1, v2)

tensor(9)

In [ ]:
torch.transpose(t1, 0, 1)

tensor([[11,  6],
        [ 5, 14],
        [ 9,  8]])

In [ ]:
t = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
t

tensor([[5., 7., 6.],
        [7., 5., 6.],
        [8., 2., 1.]])

In [ ]:
torch.det(t)

tensor(96.0000)

In [ ]:
torch.inverse(t)

tensor([[-0.0729,  0.0521,  0.1250],
        [ 0.4271, -0.4479,  0.1250],
        [-0.2708,  0.4792, -0.2500]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 2, 3],
        [1, 1, 8]])
tensor([[7, 1, 1],
        [1, 2, 9]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True,  True,  True],
        [False,  True,  True]])

### 6. Special functions

In [ ]:
t = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
t

tensor([[0., 0., 7.],
        [0., 1., 2.]])

In [ ]:
torch.log(t)

tensor([[  -inf,   -inf, 1.9459],
        [  -inf, 0.0000, 0.6931]])

In [ ]:
torch.exp(t)

tensor([[1.0000e+00, 1.0000e+00, 1.0966e+03],
        [1.0000e+00, 2.7183e+00, 7.3891e+00]])

In [ ]:
torch.sqrt(t)

tensor([[0.0000, 0.0000, 2.6458],
        [0.0000, 1.0000, 1.4142]])

In [ ]:
torch.sigmoid(t)

tensor([[0.5000, 0.5000, 0.9991],
        [0.5000, 0.7311, 0.8808]])

In [ ]:
torch.softmax(t, dim=0)

tensor([[0.5000, 0.2689, 0.9933],
        [0.5000, 0.7311, 0.0067]])

In [ ]:
torch.relu(t)

tensor([[0., 0., 7.],
        [0., 1., 2.]])